---
- name: Update linux kernel
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - pkg-config
          - libfuse-dev
          - libcap-dev
          - tmux
        state: present
        update_cache: yes

    - name: Copy data to VM
      copy:
        src: ./data/
        dest: /usr/local/bin/
        mode: '0777'
    
    # Unluckily 5.15.91 and after won't work, 5.11-5.15.90 && 5.16-5.19 works tho.
    # it comes with 5.15.125 (as of 11/18/2024)
    - name: Install Linux Kernel 5.16
      shell: /usr/local/bin/kernel_update.sh -i 5.16.20
      args:
        executable: /bin/bash
    
    - name: Update GRUB configuration
      command: update-grub

    - name: Reboot the system to apply the new kernel
      reboot:
        reboot_timeout: 300

    # Run fuse and exp commands in tmux session
    - name: Start tmux session for 'fuse'
      shell: |
        tmux new-session -d -s my_session 'cd /usr/local/bin && ./fuse /usr/local/bin/ovlcap/lower /usr/local/bin/gc'
        tmux split-window -h -t my_session 'cd /usr/local/bin && ./exp > /var/log/exp_output.log 2>&1'
      args:
        executable: /bin/bash

    - name: Wait for exp command to complete
      pause:
        seconds: 10 

    - name: Verify if exp_output.log exists on remote
      stat:
        path: /var/log/exp_output.log
      register: exp_log_status

    - name: Debug file existence
      debug:
        msg: "File exists on remote: {{ exp_log_status.stat.exists }}"

    - name: Fetch the output of ./exp if it exists
      fetch:
        src: /var/log/exp_output.log
        dest: ./exp_output.log
        flat: yes
      when: exp_log_status.stat.exists

    - name: Display the result of ./exp
      shell: cat ./exp_output.log
      register: exp_result
      delegate_to: localhost
      become: no
      when: exp_log_status.stat.exists

    - name: Debug output of ./exp
      debug:
        msg: "{{ exp_result.stdout }}"
      when: exp_log_status.stat.exists
